### PR TITLE
Extend syntax highlighting for number literals

### PR DESCRIPTION
**Pull request by jhckragh**
Should address #160. 🙂 Here's a screenshot:

flix-dec

### CODE REVIEW

**Comment by mlutze** [comment]
We also have hex integers like `0x1234`. Do/can we support those?

**Comment by jhckragh** [comment]
Should be handled now. 🙂

**Comment by mlutze** [comment]
> Should be handled now. slightly_smiling_face

Great, thanks!

**Comment by magnus-madsen** [comment]
Amazing! Quick work!

**Comment by magnus-madsen** [comment]
And deployed!

**Pull request merged**
