### PR TITLE
chore: upgrade package dependencies

### PR DESCRIPTION
**Pull request by mR4smussen**
Closes https://github.com/flix/vscode-flix/issues/232

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks @mR4smussen. Can I also ask you to add your name to `AUTHORS.md`? :)

**Comment by magnus-madsen** [comment]
@mR4smussen I see some build failures, so maybe some code has to be updated?

**Comment by mR4smussen** [comment]
It looks like i missed a breaking change regarding node-fetch v. 3, I'm currently looking into it.

**Comment by magnus-madsen** [comment]
Seems it compiles now. Can you confirm the plugin runs when you launch it?

**Comment by mR4smussen** [comment]
Yes, i can confirm that when launching the plugin in the vscode debugger it runs as expected.

**Comment by magnus-madsen** [comment]
It seems to work, but I do see this in the debug output:

```
rejected promise not handled within 1 second: Error [ERR_REQUIRE_ESM]: require() of ES Module x:\Work\GitHub\flix\vscode-flix\client\node_modules\node-fetch\src\index.js from x:\Work\GitHub\flix\vscode-flix\client\out\services\releases.js not supported.
Instead change the require of index.js in x:\Work\GitHub\flix\vscode-flix\client\out\services\releases.js to a dynamic import() which is available in all CommonJS modules.
c:\Users\iostream\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98
stack trace: Error [ERR_REQUIRE_ESM]: require() of ES Module x:\Work\GitHub\flix\vscode-flix\client\node_modules\node-fetch\src\index.js from x:\Work\GitHub\flix\vscode-flix\client\out\services\releases.js not supported.
Instead change the require of index.js in x:\Work\GitHub\flix\vscode-flix\client\out\services\releases.js to a dynamic import() which is available in all CommonJS modules.
    at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
```

Will you take a look?

**Comment by magnus-madsen** [comment]
I also see that dependabot opened some pull requests, so I guess there is a bit more work to be done.

**Pull request merged**
