### PR TITLE
fix: exclude unused files in the packaged extention for performance

### PR DESCRIPTION
**Pull request by mR4smussen**
This fixes https://github.com/flix/vscode-flix/pull/240#issuecomment-1380862531

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Does this work with vsce package?

**Comment by mR4smussen** [comment]
This PR should bring the amount of files in the packaged bundle down to around 20 files (when I run `vsce package`).

**Comment by magnus-madsen** [comment]
So, I am maybe a bit confused. We have both `client` and `server`, but I see only `client/out/extension.js`. 
Does it include both and just have a poor name?

**Comment by mR4smussen** [comment]
Thanks @magnus-madsen, I do think this was an error. I’m still new to working with bundle libraries, so when I tried to add the `server` folder to the `vscodeignore` and the extention seemed to work I simply ran with it... I have now gone through the `client/out/extension.js` and you are correct that the `server` branch was not included in this, so I made a new commit where we bundle both the `client` and the `server` branch, and we use a new `dist` folder as our output folder, since it doesn't make sense for it to be in a `client/out` folder.

**Comment by magnus-madsen** [comment]
Ok. Can you confirm that if you run vsce package that the vsix package works when installed?

**Comment by magnus-madsen** [comment]
This would be the best way to test before i deploy

**Comment by mR4smussen** [comment]
Previously the vsix package didn't works when installed. It seems like we were expecting the compiled server code to be in `server/out/server.js` (hardcoded somewhere). I wasn't able to find where this value was set but moving the bundled files into `client/out/extension.js` and `server/out/server.js` seems to fix the problem.

I can confirm that after the latest commit I can use `vsce package` --> install the new vsix package --> reload vscode --> start flix and run a .flix file.

**Comment by magnus-madsen** [comment]
Seems to work. I deployed it 👍

**Pull request merged**
