### PR TITLE
feat: add `Show AST` button

### PR DESCRIPTION
**Pull request by mR4smussen**
This should not be merged before the compiler side can handle the request. I'm currently working on the compiler side of this issue and by faking a few things I have been able to test that this commit should work.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Screenshot?

**Comment by mR4smussen** [comment]
Currently when right clicking in the editor window we have a button `Show AST`. I don't know how many kinds of ASTs we should be able to show (https://github.com/flix/flix/pull/5559#issuecomment-1453439816) but we could change this to either use sub-menus (like the peek option in the screenshot) or prompt the user for an input?
image

**Comment by magnus-madsen** [comment]
@JonathanStarup Maybe you can chime in on what we should do?

(Perhaps we should just have a fixed list of phases/things to show). It seems easier than asking the server.

**Comment by magnus-madsen** [comment]
We have a lot of hardcoded things anyway, so I think we should just assume a fixed list of things.

Thus lets go with a menu of hardcoded items. 

We can start with "TypedAst" in the list.

**Comment by mR4smussen** [comment]
Now we have a sub-menu where the specific sub-menu items decides which phase is parsed to the [showAst method](https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala#L35). (In the screenshot below I'm using a print statement in the showAst method printing the phase argument)
image

**Comment by magnus-madsen** [comment]
Looks good. Then we just need the compiler side.

**Comment by magnus-madsen** [comment]
Once https://github.com/flix/flix/pull/5565 is merged, I believe this should be possible to test.

**Comment by magnus-madsen** [comment]
> I think this works. At least both the `id` and the `phase` is sent to the request on the compiler side, and in turn the `showAst` method is called with the correct `phase` argument. I’m not sure what is supposed to happened when the items are clicked, are we not still faking the behavior of the `showAst` method?

Then we should open a new Window/tag with the content that is returned from the compiler.

**Comment by mR4smussen** [comment]
I wasn’t completely sure what you ment by a new Window/tag, but I have made something. I realised I wasn’t sending the result back from the server to the client, so I changed the response handler. On the client side I made it open a new window with the result from the request.
(Result of clicking the `Typed Ast` button in the previous image)
image

**Comment by magnus-madsen** [comment]
Looks good, I would say!

What happens if you click twice, you get two windows right?

> Also, I made the sub-menu only be visible when editing a flix document, I wasn't sure if this was the intention?

That seems reasonable.

**Comment by mR4smussen** [comment]
Correct, if you go back to the flix document and clicks the Show Ast button again it opens another window.

**Comment by JonathanStarup** [comment]
@mR4smussen the ast for the whole program might be very large (30k lines without treeshaking) so we need to filter the ast somehow. We could either pass in a file to the ast request or pass in a namespace. What do you think would be nicest/easiest to add in vscode?

**Comment by mR4smussen** [comment]
I think I can get access to the path of the file currently open. Otherwise, I can prompt the user for a file (like the image below). Here I can make the workstation path be filled in automatically, so it would be equivalent to them giving us a relative path. (I’m not completely sure what the namespace would be)

image

**Comment by JonathanStarup** [comment]
The path stored in the sourcelocation is the relative path, so receiving that would be easy to filter

**Comment by magnus-madsen** [comment]
Can we send the URI of the currently opened file? 

Then we can do the filtering server side.

**Comment by mR4smussen** [comment]
I believe this latest commit should include the URI in the request. Obviously, this also requires the compiler side to parse the URI for it to work.

For my test I got this to work with the changes below, but you might know of a better way.

In https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/Request.scala#L392-L397:
parseShowAst


In https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala#L315-L319:
requestShowAstProvider

In https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala#L35:
showAst

**Comment by magnus-madsen** [comment]
@JonathanStarup Will you incorporate these changes on the server side?

**Pull request merged**
