### PR TITLE
Syntax highlight type names and defs

### PR DESCRIPTION
**Pull request by jhckragh**
The attached image shows before and after this change (lower half is before; upper half is after).

I agree to release this contribution under the Apache 2.0 license.

flix-highlight-def

### CODE REVIEW

**Comment by magnus-madsen** [comment]
You are welcome to add your name to `AUTHORS.md`, but if you prefer not to that is also OK.

**Comment by magnus-madsen** [comment]
Is the screenshot with/without Flixfy dark? What does it look like in the "other one"?

**Comment by jhckragh** [comment]
Thanks for taking a look. 🙂 Per your response I've changed some scope names to match those that are used by most other themes. Here's a new image showing how it looks in some of the builtin themes.

flix-highlight-def0

**Comment by magnus-madsen** [comment]
Nice! Looks good :)

**Comment by magnus-madsen** [comment]
The plugin usually takes 1 hour to update then it should be available.

**Pull request merged**
