### PR TITLE
Add completionHandler

### PR DESCRIPTION
**Pull request by manoj2601**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Looks good! Can I ask you to:

- Add your name to `AUTHORS.md`.
- Help add suggestions to this ticket: https://github.com/flix/flix/issues/1977 
- Test what happens if you run your updated VSCode plugin with an old version of Flix (e.g. go to https://flix.dev/nightly/ and grab an old version). Does it crash?

**Comment by magnus-madsen** [comment]
I am confused. Why is the sample code in the pull request?

**Comment by manoj2601** [comment]
Sample code was meant to add some snipets manually to the client-side only. This is in case any snippet throws an error while sending an object of `completionItem` from the compiler to the plugin, then we can add such snippets to the client-side directly.
Removing it since this case is rare.

**Comment by manoj2601** [comment]
With an older version of flix, it runs but when we go for `trigger suggest`, it shows it an unsupported request since `JString(lsp/complete)` is not added in the compiler.
Hence, it does not crash and runs well.
Output for `trigger suggest` request:
`Unsupported request: 'JString(lsp/complete)'.
Job timed out after 30 seconds`

**Comment by magnus-madsen** [comment]
> With an older version of flix, it runs but when we go for `trigger suggest`, it shows it an unsupported request since `JString(lsp/complete)` is not added in the compiler.
> Hence, it does not crash and runs well.
> Output for `trigger suggest` request:
> `Unsupported request: 'JString(lsp/complete)'. Job timed out after 30 seconds`

OK. Does the plugin still work after this error? For example can you still hover over an expression as see its type?

**Comment by manoj2601** [comment]
The plugin doesn't work until the current job (request for `trigger suggest`) is timed out (a duration of 30 seconds). After 30 seconds, it begins to work the same as before.

**Comment by magnus-madsen** [comment]
> The plugin doesn't work until the current job (request for `trigger suggest`) is timed out (a duration of 30 seconds). After 30 seconds, it begins to work the same as before.

OK. Not great, but we can leave that for later. I am going to merge it now!

Please have a look at https://github.com/flix/flix/issues/1977 and sketch as many ideas as you can come up with :)

**Pull request merged**
