### PR TITLE
feat: report compiler crash

### PR DESCRIPTION
**Pull request by mR4smussen**
related to https://github.com/flix/vscode-flix/issues/202

This adds a popup (like the image below) when a crash occurs on the compiler side. 
My `_.isEqual(result, {})` check is a bit of a hack, and it kind of requires that we don't send empty diagnostic-results back unless it's from a crash.
If we want a better solution for this the language server would need to send either some more information back or we would need to send some special “crash” status back (which could lead to some other problems).

image

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Can we inspect the status flag here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala#L357

**Comment by mR4smussen** [comment]
The value of that status flag (currently "failure") becomes the value of the `status` argument here: 
https://github.com/flix/vscode-flix/blob/master/server/src/handlers/handlers.ts#L315

Currently I can't really use the "failure" since this is obviously used elsewhere, so I'm using the result property.

**Comment by magnus-madsen** [comment]
> 

Ah okay. It sounds like we should change the compiler to give more information. Ill look into that (but might be a bit, because I am going on vacation soon).

**Comment by magnus-madsen** [comment]
Needs compiler change.

**Pull request closed without merging**
