### PR TITLE
fix: Ensure that "Flix Restart" works

### PR DESCRIPTION
**Pull request by mR4smussen**
As expected, the issue with the restart action was caused by it closing the compiler, in turn calling another restart, which created a loop until something timed out. I tried to find a way to distinguish different close events (errors from premeditated socket.close() calls) but here I agree with https://github.com/flix/vscode-flix/pull/92#issuecomment-774709599, that this didn't immediately seem possible. I ended up making a solution with timestamps, which seems to work for what we need right now.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Roger. So with this PR both standby and restart should work well?

Did you use the process manager to see how many Java instances end up running?

**Comment by mR4smussen** [comment]
> Roger. So with this PR both standby and restart should work well?

Yes, I tested both of these
> Did you use the process manager to see how many Java instances end up running?

I didn't try this, I can do that right now

**Comment by mR4smussen** [comment]
I have tested this solution by running a lot of "Flix Restarts" and had my pc come back from standby a couple of times and still I only have two Java instances running, which I believe is expected. One as a sub-process for vs-code (probably for the "Output" tab) and one as a separate process (probably the main REPL we have running for the "Terminal" output)

**Comment by magnus-madsen** [comment]
> I have tested this solution by running a lot of "Flix Restarts" and had my pc come back from standby a couple of times and still I only have two Java instances running, which I believe is expected. One as a sub-process for vs-code (probably for the "Output" tab) and one as a separate process (probably the main REPL we have running for the "Terminal" output)

Sounds right! Thanks.

I will merge this once I get home.

**Pull request merged**
