### PR TITLE
fix: Package Commands

### LINKED ISSUE #26: Package Init Times out
But it should do something:

image

Maybe the command is misnamed?

### PR DESCRIPTION
**Pull request by plougsgaard**
- Adds missing parameter to package commands

Fixes #26

### CODE REVIEW

**Review by magnus-madsen — COMMENTED** [review]
This looks reasonable to me, but I was not able to determine if it shows the output of the package command anywhere? That will be important for the user to understand what is going on.

**Comment by plougsgaard** [comment]
> This looks reasonable to me, but I was not able to determine if it shows the output of the package command anywhere? That will be important for the user to understand what is going on.

See `makeRunPackageCommandResponseHandler`. It will print the response on success. However I haven't seen this myself because I don't have a proper test case for packages yet.

**Comment by magnus-madsen** [comment]
> > This looks reasonable to me, but I was not able to determine if it shows the output of the package command anywhere? That will be important for the user to understand what is going on.
> 
> See `makeRunPackageCommandResponseHandler`. It will print the response on success. However I haven't seen this myself because I don't have a proper test case for packages yet.

You can try package `init` - that should work

**Comment by plougsgaard** [comment]
`pkg/init` responds with `{ id: '<id>', status: 'success' }` - it creates a lot of files and crashes if any of the files already exist.

**Comment by magnus-madsen** [comment]
> `pkg/init` responds with `{ id: '<id>', status: 'success' }` - it creates a lot of files and crashes if any of the files already exist.

That sounds approximately right. The package system is not really implemented yet, so as long something happens and status is reported back that is fine. 

Do you want me to merge?

**Comment by plougsgaard** [comment]
> Do you want me to merge?

Squash or approve review. 🥇

**Review by magnus-madsen — APPROVED** [review]

**Pull request merged**
