### PR TITLE
feat: inlay hints support

### PR DESCRIPTION
**Pull request by nicdard**
https://github.com/flix/flix/pull/3415

The communication seems to work properly, I still need to add more functionalities to the provider to check whether everything is fine.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
FYI: This can be merged once the compiler support is merged *and* we have released the next version of Flix. (Otherwise we would break the plugin.)

**Comment by magnus-madsen** [comment]
Do you have some nice screenshots? :)

**Comment by nicdard** [comment]
> FYI: This can be merged once the compiler support is merged _and_ we have released the next version of Flix. (Otherwise we would break the plugin.)

Sure!

**Comment by nicdard** [comment]
> Do you have some nice screenshots? :)

I am gonna post some soon 👀

**Comment by nicdard** [comment]
> > Do you have some nice screenshots? :)
> 
> I am gonna post some soon eyes

So, I have tried this branch with the one in the compiler, but apparently no inlay hints are displayed for local variable (let statements). However the compiler together with the extension are working properly and the communication works. I'll try to debug the compiler now

**Comment by nicdard** [comment]
I have found the error in the Language Server, fixing it  [here](https://github.com/flix/flix/pull/3415)

**Comment by nicdard** [comment]
> I have found the error in the Language Server, fixing it [here](https://github.com/flix/flix/pull/3415)

It's now ready :)
Screenshot from 2022-07-03 02-30-08

**Comment by magnus-madsen** [comment]
Plan: 

- Iterate and merge the flix/flix PR.
- Wait for a new release of Flix.
- Then merge the flix/vscode-flix PR and release a new version of the extension.

(This is to ensure that we don't cause breakages on the user side).

**Comment by magnus-madsen** [comment]
This appears to break something with source locations related to diagnostics.

**Comment by magnus-madsen** [comment]
I can't reproduce it now, but I had some strange behavior.

**Comment by nicdard** [comment]
> I can't reproduce it now, but I had some strange behavior.

What type of strange behavior? Does it have anything to do with the position of the disgnostics?

**Comment by magnus-madsen** [comment]
> > I can't reproduce it now, but I had some strange behavior.
> 
> What type of strange behavior? Does it have anything to do with the position of the disgnostics?

Ill try to reproduce later.

**Comment by nicdard** [comment]
> > > I can't reproduce it now, but I had some strange behavior.
> > 
> > 
> > What type of strange behavior? Does it have anything to do with the position of the disgnostics?
> 
> Ill try to reproduce later.

Ok thanks :)

**Comment by magnus-madsen** [comment]
Inlay hints now available in Flix stable! :)

**Pull request merged**
