### PR TITLE
Highlight the contents of ${...} recursively

### PR DESCRIPTION
**Pull request by jhckragh**
As discussed in #133. The following screenshot shows the result with the current master version of Flix. 🙂

flix-str-rec

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks. But I don't understand the change. How does it work?

**Comment by jhckragh** [comment]
My understanding/intuition: Within a begin/end pattern you can have a `"patterns"` clause, and the patterns listed in this clause will be applied to the region between the begin/end matches:

flix-str-rec-grm

My idea is to introduce a new aggregate pattern called `"all_patterns"`, which includes all the existing patterns. Then I include this in the `"patterns"` clause for `${...}`. The effect is that all the patterns that work at the top level will also be applied inside `${...}`. 🙂

**Comment by magnus-madsen** [comment]
> 
> 
> My understanding/intuition: Within a begin/end pattern you can have a `"patterns"` clause, and the patterns listed in this clause will be applied to the region between the begin/end matches:
> 
> flix-str-rec-grm
> 
> My idea is to introduce a new aggregate pattern called `"all_patterns"`, which includes all the existing patterns. Then I include this in the `"patterns"` clause for `${...}`. The effect is that all the patterns that work at the top level will also be applied inside `${...}`. 🙂

OK, and this should not have any bad performance implications? (or no idea?)

**Comment by jhckragh** [comment]
I don't think this really impacts performance measurably. Instead of directly applying the patterns listed in the top-level `"patterns"` clause, the engine will apply the `"#all_patterns"` include, which simply consists of the patterns that used to be in the top-level `"patterns"` clause. So it simply introduces a single indirection step. Of course, highlighting the content of `${...}` recursively will be slower than not doing it. But as I mentioned in #133, the builtin TypeScript extension does this recursive highlighting, and it seems plenty fast even for very large codebases. 😉

**Comment by magnus-madsen** [comment]
Nice!

**Pull request merged**
