### PR TITLE
Add jars from lib folder to classpath

### PR DESCRIPTION
**Pull request by mlutze**
(I don't really know what I'm doing, but it seems to work)

It seems the LSP launch command and the build commands are separate, so if we accept this idea, we'll have to change the build commands as well.

Unfortunately, you have to relaunch every time a jar is added, but that's unavoidable as far as I can tell.

### CODE REVIEW

**Comment by jhckragh** [comment]
Looks good! 🙂 However, if I remember correctly, the symbol for separating parts of the classpath depends on the underlying platform: it's `:` on Unix and `;` on Windows: https://stackoverflow.com/questions/60211687/how-to-get-java-classpath-separator. So I guess that needs to be handled somehow.

**Comment by mlutze** [comment]
> Looks good! slightly_smiling_face However, if I remember correctly, the symbol for separating parts of the classpath depends on the underlying platform: it's `:` on Unix and `;` on Windows: https://stackoverflow.com/questions/60211687/how-to-get-java-classpath-separator. So I guess that needs to be handled somehow.

Oh, good catch, I didn't know that!

**Comment by magnus-madsen** [comment]
What's the goal? To suck jars into Flix?

**Comment by magnus-madsen** [comment]
but per project and only from lib, right?

**Comment by mlutze** [comment]
> What's the goal? To suck jars into Flix?

Yes. The use case is that one of Stephen's projects that I want to consume has a Java dependency.



> but per project and only from lib, right?

Right!

**Comment by jhckragh** [comment]
Good use of `path.delimiter`; I didn't know about that one! 🙂 It seems to be pretty close now, but on Windows the classpath turns out like this:

```
file:///c%3A/Users/jacob/FlixTest/lib/guava-31.0.1-jre.jar;c:\Users\jacob\FlixTest\flix.jar
```

while in this case it should be:

```
c:\Users\jacob\FlixTest\lib\guava-31.0.1-jre.jar;c:\Users\jacob\FlixTest\flix.jar
```

I think the `vsCodeUriToUriString` call must be replaced with something else. 🤔

**Comment by mlutze** [comment]
@jhckragh Thanks for the review. I changed it to use `uri.fsPath`, which _seems_ to be the right thing according to the docs, but I'm not sure. It's also hard to test without a windows machine. Let me know if this still doesn't work and/or if you have suggestions for a better way to address this.

**Comment by jhckragh** [comment]
You're welcome! 🙂 I just tried out the latest commit and got this classpath:

```
file:///c:/Users/jacob/FlixTest/lib/guava-31.0.1-jre.jar;c:\Users\jacob\FlixTest\flix.jar
```

I think the body of `vsCodeUriToTerminalString`,

```
return vscode.Uri.file(uri.path).toString(true)
```

 should be replaced with:

```
return uri.fsPath
```

**Comment by magnus-madsen** [comment]
RFR?

**Comment by mlutze** [comment]
> RFR?

Yes, though two caveats:
1. I still don't know if it works on Windows
2. There's a bit of copy-paste; I don't know my way around the codebase too well, so I'm not sure where such utilities should go.

**Comment by jhckragh** [comment]
I've just come home from work and tried out the latest changes. It looks like the LSP launch command works correctly now; there are no errors about missing classes. 🥳

flix-jars

But it seems that there are some further Windows quirks to deal with when it comes to the build command. If one uses `cmd` as terminal in VSCode, then the "run" button works (the sample code yields the expected output `a`):

cmd

But if one instead uses PowerShell as terminal, then it doesn't work:

ps0

It looks like the problem is that the classpath must be quoted:

ps1

Adding quotes manually will interfere with the `shell-quote` library that's used in the extension, so probably some workaround is required. Good ol' Windows! 😅

**Comment by mlutze** [comment]
Thanks again for testing!

Would it be reasonable to merge this onto a development branch and have someone with a Windows machine take over?

**Comment by magnus-madsen** [comment]
I'd rather not merge something that (potentially) break master because then I cannot easily release new versions.

**Comment by magnus-madsen** [comment]
Do the commands currently work in PowerShell?

**Comment by magnus-madsen** [comment]
Question: Maybe the Flix compiler itself should have a mechanism to load class files inside `lib`. Would that not be better than relying on the classpath?

**Comment by jhckragh** [comment]
> Do the commands currently work in PowerShell?

Yes:

ps2

Oddly enough, the trouble seems to be the path delimiter, which PowerShell apparently treats as a command separator and hence requires quoting for. Seems like a bit of a rough spot in the VSCode API in my opinion. There's been some discussion - https://github.com/microsoft/vscode/issues/108550 - but apparently no API has been provided to deal with these pesky terminal differences. 🤔

**Comment by mlutze** [comment]
> Question: Maybe the Flix compiler itself should have a mechanism to load class files inside `lib`. Would that not be better than relying on the classpath?

Yes, definitely. But I thought we were pretty far from being able to do that.

**Comment by jhckragh** [comment]
Returning to the PowerShell issue: I think a solution would be to just add `"` around the classpath; that should work on all shells. Something along these lines:

```
terminal.sendText(baseCmd + " " + quote(args))
```

where `baseCmd` would be

```
java -cp "..."
```

**Comment by mlutze** [comment]
Thanks for the help, @jhckragh

I'm going to close this since I think we'll take this in a different direction with dynamic class loading in the Flix compiler.

**Pull request closed without merging**
